INSERT INTO public.tier_features (tier, feature_key, is_allowed) VALUES
  ('starter','boardExport',true),
  ('starter','anomalyDetection',false),('starter','forecasting',false),('starter','causalInference',false),
  ('starter','benchmarking',false),('starter','alertPlaybooks',false),('starter','okrAlignment',false),
  ('starter','aicisIntegration',false),('starter','apiIntegrations',false),('starter','auditExport',false),
  ('starter','livestream',false),('starter','convergence',false),('starter','biasDetection',false),
  ('starter','counterfactual',false),('starter','executiveConvergence',false),('starter','commandCenter',false),
  ('starter','scenarioBranching',false),('starter','dataLineage',false),('starter','marketIntelligence',false),
  ('starter','multiOrg',false),('starter','onPremise',false),('starter','decisionLedger',true),
  ('growth','causalInference',true),('growth','benchmarking',true),('growth','alertPlaybooks',true),
  ('growth','okrAlignment',true),('growth','aicisIntegration',true),('growth','auditExport',true),
  ('growth','livestream',true),('growth','convergence',true),('growth','decisionLedger',true),
  ('growth','biasDetection',false),('growth','counterfactual',false),('growth','executiveConvergence',false),
  ('growth','commandCenter',false),('growth','scenarioBranching',false),('growth','dataLineage',false),
  ('growth','marketIntelligence',false),('growth','multiOrg',false),('growth','onPremise',false),
  ('enterprise','causalInference',true),('enterprise','benchmarking',true),('enterprise','alertPlaybooks',true),
  ('enterprise','okrAlignment',true),('enterprise','aicisIntegration',true),('enterprise','auditExport',true),
  ('enterprise','livestream',true),('enterprise','convergence',true),('enterprise','decisionLedger',true),
  ('enterprise','executiveConvergence',true),('enterprise','scenarioBranching',true),
  ('enterprise','dataLineage',true),('enterprise','marketIntelligence',true),('enterprise','onPremise',true),
  ('enterprise','anomalyDetection',true),('enterprise','forecasting',true),('enterprise','apiIntegrations',true),
  ('enterprise','biasDetection',true),('enterprise','counterfactual',true),('enterprise','commandCenter',true),
  ('enterprise','multiOrg',true)
ON CONFLICT (tier, feature_key) DO UPDATE SET is_allowed = EXCLUDED.is_allowed;