// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
import { clientEnv, validateClientEnv } from '@/lib/env';

validateClientEnv();

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(
  clientEnv.supabaseUrl,
  clientEnv.supabasePublishableKey,
  {
    auth: {
      storage: localStorage,
      persistSession: true,
      autoRefreshToken: true,
      // PKCE flow for OAuth (Google, SAML) — prevents authorization code interception attacks
      flowType: 'pkce',
      // Detect session in URL (required for PKCE callback handling)
      detectSessionInUrl: true,
      // Suppress debug logs in production (avoids token leakage in console)
      debug: false,
    },
  }
);
